# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/set_model.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetModel(object):
    def setupUi(self, SetModel):
        SetModel.setObjectName("SetModel")
        SetModel.resize(549, 176)
        self.centralwidget = QtWidgets.QWidget(SetModel)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setEnabled(False)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout.addWidget(self.btn_clear, 4, 2, 1, 1)
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setEnabled(True)
        self.btn_start.setObjectName("btn_start")
        self.gridLayout.addWidget(self.btn_start, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 4, 0, 1, 1)
        self.cb_edit = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_edit.setObjectName("cb_edit")
        self.gridLayout.addWidget(self.cb_edit, 3, 0, 1, 3)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 0, 1, 3)
        self.btn_set = QtWidgets.QPushButton(self.centralwidget)
        self.btn_set.setEnabled(False)
        self.btn_set.setObjectName("btn_set")
        self.gridLayout.addWidget(self.btn_set, 4, 1, 1, 1)
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setEnabled(False)
        self.btn_stop.setObjectName("btn_stop")
        self.gridLayout.addWidget(self.btn_stop, 2, 1, 1, 2)
        SetModel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SetModel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 549, 31))
        self.menubar.setObjectName("menubar")
        SetModel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SetModel)
        self.statusbar.setObjectName("statusbar")
        SetModel.setStatusBar(self.statusbar)

        self.retranslateUi(SetModel)
        self.btn_clear.clicked.connect(self.lineEdit.clear) # type: ignore
        self.btn_start.clicked['bool'].connect(self.btn_stop.setDisabled) # type: ignore
        self.btn_stop.clicked['bool'].connect(self.btn_start.setDisabled) # type: ignore
        self.btn_start.clicked['bool'].connect(self.btn_start.setEnabled) # type: ignore
        self.btn_stop.clicked['bool'].connect(self.btn_stop.setEnabled) # type: ignore
        self.cb_edit.toggled['bool'].connect(self.lineEdit.setEnabled) # type: ignore
        self.cb_edit.toggled['bool'].connect(self.btn_clear.setEnabled) # type: ignore
        self.cb_edit.toggled['bool'].connect(self.btn_set.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SetModel)

    def retranslateUi(self, SetModel):
        _translate = QtCore.QCoreApplication.translate
        SetModel.setWindowTitle(_translate("SetModel", "SetModel"))
        self.btn_clear.setText(_translate("SetModel", "Clear"))
        self.btn_start.setText(_translate("SetModel", "Start"))
        self.cb_edit.setText(_translate("SetModel", "Edit"))
        self.btn_set.setText(_translate("SetModel", "Set"))
        self.btn_stop.setText(_translate("SetModel", "Stop"))
